on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  APPLICATION_PUBLISH_PROFILE: ${{ secrets.NEW_SECRET }}
  WEBAPP_NAME: "website"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build
          mkdir -p ./build/standalone
          mv ./build/static ./build/standalone/build || echo "Skipping move"
          mv ./public ./build/standalone || echo "Skipping move"

      - name: Fix file permissions
        run: chmod -R 755 ./build/standalone

      - name: Debug folder structure
        run: ls -la ./build/standalone

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: "Production"
          publish-profile: ${{ env.APPLICATION_PUBLISH_PROFILE }}
          package: ./build/standalone

      - name: Restart Azure Web App
        run: |
          az webapp restart --name ${{ env.WEBAPP_NAME }} --resource-group YOUR_RESOURCE_GROUP
